AXFDay/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("App.urls",namespace="axf")),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/',views.home,name="home"),
    url(r'^market/',views.market,name="market"),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/',views.market_With_params,name="market_with_params"),
    url(r'^cart/',views.cart,name="cart"),
    url(r'^mine/',views.mine,name="mine"),
    url(r'^userregister/',views.user_Register,name="userregister"),
    url(r'^userlgout/',views.userlgout,name='userlgout'),
    url(r'^checkuser/',views.check_user,name='check_user'),
    url(r'^checkemail/',views.check_email,name='check_email'),
    url(r'^userlogin/',views.user_login,name='userlogin'),
    url('r^activeaccount/',views.active_account,name='activeaccount'),
    url(r'^addtocart/', views.add_to_cart, name='add_to_cart'),
    url(r'^subtocart/', views.sub_to_cart, name='sub_to_cart'),
    url(r'^changecartstatus/',views.change_cart_status,name='change_cart_status'),
    url(r'^changecartsstatus/',views.change_carts_status,name='change_carts_status'),
    url(r'^makeorder/',views.make_order,name='make_order'),
    url(r'^orderdetail/',views.order_detail,name='orderdetail'),
    url(r'^alipaycallback/',views.alipay_callback,name='alipaycallback'),
    url(r'^orderlist/',views.order_list,name='order_list'),



]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name ="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block extCSS %}

    {% endblock %}
</head>
<body>

    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src ="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% block extJS %}

    {% endblock %}
</body>
</html>

templates/base/base_main.html
{% extends "base/base.html" %}
{% load static %}
{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

templates/base/base_order.html
{% extends 'base/base.html' %}

templates/base/base_user.html
{% extends 'base/base.html' %}
{% load static %}
{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/../../../Python1803/static/js/md5.js'%}"></script>
{% endblock %}