AXFDay/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("App.urls",namespace="axf")),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/',views.home,name="home"),
    url(r'^market/',views.market,name="market"),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/',views.market_With_params,name="market_with_params"),
    url(r'^cart/',views.cart,name="cart"),
    url(r'^mine/',views.mine,name="mine"),
    url(r'^userregister/',views.user_Register,name="userregister"),
    url(r'^userlgout/',views.userlgout,name='userlgout'),
    url(r'^checkuser/',views.check_user,name='check_user'),
    url(r'^checkemail/',views.check_email,name='check_email'),
    url(r'^userlogin/',views.user_login,name='userlogin'),
    url('r^activeaccount/',views.active_account,name='activeaccount'),
    url(r'^addtocart/', views.add_to_cart, name='add_to_cart'),
    url(r'^subtocart/', views.sub_to_cart, name='sub_to_cart'),
    url(r'^changecartstatus/',views.change_cart_status,name='change_cart_status'),
    url(r'^changecartsstatus/',views.change_carts_status,name='change_carts_status'),
    url(r'^makeorder/',views.make_order,name='make_order'),
    url(r'^orderdetail/',views.order_detail,name='orderdetail'),
    url(r'^alipaycallback/',views.alipay_callback,name='alipaycallback'),
    url(r'^orderlist/',views.order_list,name='order_list'),



]

templates/market/market.html
{% extends "base/base_main.html" %}
{% load  static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/css/market.css' %}">
{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="{% static 'app/market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="market">
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        <a href="{% url 'axf:market_with_params' foodtype.typeid 0 0 %}">{{ foodtype.typename }}</a>
                        {% ifequal foodtype.typeid categoryid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}

            </ul>


        </aside>
        <section>
            <nav>
                <ul>
                    <li id="all_types">
                        <span>全部分类<span class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                    <li id="sort_rule">
                        <span>综合排序 <span class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for goods in goods_list %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}" alt="{{ goods.productname }}">
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <p class="unit">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span>￥{{ goods.price }}</span>
                                        <s>{{ goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>
                            <section>
                                <button class="subShoping">—</button>
                                <span>0</span>
                                <button class="addShoping" goodsid="{{ goods.id }}">+</button>
                            </section>
                        </li>
                    {% endfor %}

                </ul>

                <div id="all_type_container">
                    <div>
                        {% for child_type_name in child_type_name_list %}
                            {% ifequal childcid child_type_name.1 %}
                                <a href="{% url 'axf:market_with_params' categoryid child_type_name.1 0 %}">
                                    <button class="btn btn-default btn-danger">{{ child_type_name.0 }}</button>
                                </a>
                            {% else %}
                                <a href="{% url 'axf:market_with_params' categoryid child_type_name.1 0 %}">
                                    <button class="btn btn-default">{{ child_type_name.0 }}</button>
                                </a>
                            {% endifequal %}
                        {% endfor %}

                    </div>
                </div>

                <div id="sort_rule_container">
                    <div>
                        <a href="{% url 'axf:market_with_params' categoryid childcid 0 %}">
                            <span>综合排序</span>
                        </a>

                        <a href="{% url 'axf:market_with_params' categoryid childcid 1 %}">
                            <span>价格升高</span>
                        </a>

                        <a href="{% url 'axf:market_with_params' categoryid childcid 2 %}">
                            <span>价格降低</span>
                        </a>

                    </div>
                </div>
            </menu>
        </section>
    </div>
{% endblock %}