AXFDay/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("App.urls",namespace="axf")),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/',views.home,name="home"),
    url(r'^market/',views.market,name="market"),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/',views.market_With_params,name="market_with_params"),
    url(r'^cart/',views.cart,name="cart"),
    url(r'^mine/',views.mine,name="mine"),
    url(r'^userregister/',views.user_Register,name="userregister"),
    url(r'^userlgout/',views.userlgout,name='userlgout'),
    url(r'^checkuser/',views.check_user,name='check_user'),
    url(r'^checkemail/',views.check_email,name='check_email'),
    url(r'^userlogin/',views.user_login,name='userlogin'),
    url('r^activeaccount/',views.active_account,name='activeaccount'),
    url(r'^addtocart/', views.add_to_cart, name='add_to_cart'),
    url(r'^subtocart/', views.sub_to_cart, name='sub_to_cart'),
    url(r'^changecartstatus/',views.change_cart_status,name='change_cart_status'),
    url(r'^changecartsstatus/',views.change_carts_status,name='change_carts_status'),
    url(r'^makeorder/',views.make_order,name='make_order'),
    url(r'^orderdetail/',views.order_detail,name='orderdetail'),
    url(r'^alipaycallback/',views.alipay_callback,name='alipaycallback'),
    url(r'^orderlist/',views.order_list,name='order_list'),



]

templates/mine/mine.html
{% extends "base/base_main.html" %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/css/mine.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}


{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                <span>
                    <img src="{{ user_icon }}" alt ="icon">
                </span>
                {% else %}
                    <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            
            {% if is_login %}
                <p>{{ user_name }}</p>
                {% else %}
                <p><a href="{% url 'axf:userlogin' %}">未登录</a></p>
            {% endif %}
                
            <p class="level">
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>
            {% if is_login %}

            {% else %}
                <div id="regis">
                    <a href="{% url 'axf:userregister' %}">注册</a>
                </div>
            {% endif %}

            <p class="collect">
                <span class="glyphicon glyphicon-heart"></span>
                <span>收藏</span>
            </p>
        </div>

        <div class="mine_info">
            <p>
                <span>我的订单</span>
                <a href="#">查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <dl id="wait_pay">
                            <span class="count badge">{{ order_wait_pay_no }}</span>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>

                            </dt>
                            <dd>待付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <span class="count badge">{{ order_sended_no }}</span>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>


            </nav>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{%  url 'axf:userlgout' %}">退出当前登录</a>
                </p>
            {% endif %}
        </div>


    </div>
{% endblock %}